version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
    environment:
      POSTGRES_HOST: postgres
  
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker-testing'
    ports:
      - '4321:5432'

  # redis-server:
  #   image: 'redis'



